"""empty message

Revision ID: 2c023d292c6a
Revises: 
Create Date: 2022-03-01 01:34:51.856901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c023d292c6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_income', sa.Float(), nullable=False),
    sa.Column('max_income', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dop', sa.DateTime(), nullable=False),
    sa.Column('premium', sa.Float(), nullable=False),
    sa.Column('body_injury_libality', sa.Boolean(), nullable=False),
    sa.Column('personal_injury_protection', sa.Boolean(), nullable=False),
    sa.Column('property_damage_libality', sa.Boolean(), nullable=False),
    sa.Column('collision', sa.Boolean(), nullable=False),
    sa.Column('comprehensive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vechile_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('Fuel', sa.Enum('CNG', 'Petrol', 'Diesel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vechile_segments')
    op.drop_table('policies')
    op.drop_table('income_group')
    # ### end Alembic commands ###
