"""empty message

Revision ID: 5ff4ba83bb2c
Revises: 6e46c0f7454f
Create Date: 2022-03-01 01:57:05.615163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ff4ba83bb2c'
down_revision = '6e46c0f7454f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vechile_segments', 'Fuel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vechile_segments', sa.Column('Fuel', mysql.ENUM('CNG', 'Petrol', 'Diesel'), nullable=False))
    # ### end Alembic commands ###
