"""empty message

Revision ID: c8dca2f6ca36
Revises: cb30b11b31fd
Create Date: 2022-03-01 04:20:59.565165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8dca2f6ca36'
down_revision = 'cb30b11b31fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('customers_ibfk_2', 'customers', type_='foreignkey')
    op.drop_column('customers', 'policy_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('policy_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('customers_ibfk_2', 'customers', 'policies', ['policy_id'], ['id'], ondelete='CASCADE')
    op.drop_table('customer_policies')
    # ### end Alembic commands ###
