"""empty message

Revision ID: cb30b11b31fd
Revises: da4d5e95add9
Create Date: 2022-03-01 04:07:04.150689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb30b11b31fd'
down_revision = 'da4d5e95add9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'gender',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Enum('Male', 'Female', 'Transgender'),
               existing_nullable=False)
    op.alter_column('customers', 'customer_region',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Enum('East', 'West', 'North', 'South'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'customer_region',
               existing_type=sa.Enum('East', 'West', 'North', 'South'),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=False)
    op.alter_column('customers', 'gender',
               existing_type=sa.Enum('Male', 'Female', 'Transgender'),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###
