"""empty message

Revision ID: da4d5e95add9
Revises: 5ff4ba83bb2c
Create Date: 2022-03-01 01:58:44.927528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4d5e95add9'
down_revision = '5ff4ba83bb2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.Enum('CNG', 'Petrol', 'Diesel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vechiles_fuels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vechile_id', sa.Integer(), nullable=False),
    sa.Column('fuel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fuel_id'], ['fuels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vechile_id'], ['vechile_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vechiles_fuels')
    op.drop_table('fuels')
    # ### end Alembic commands ###
